export const COMMON_PERMISSIONS = {
  LOGGED_IN: 'LOGGED_IN',
  GUEST: 'GUEST',
  PRIMARY_CONTACT: 'PRIMARY_CONTACT',
};

export const CLIENT_PERMISSIONS = {
  // Team
  VIEW_USER_LIST: 'VIEW_USER_LIST',
  ADD_USER: 'ADD_USER',
  UPDATE_USER: 'UPDATE_USER',
  REMOVE_USER: 'REMOVE_USER',
  VIEW_USER_DETAIL: 'VIEW_USER_DETAIL',

  // Partner
  ADD_NEW_PARTNER: 'ADD_NEW_PARTNER',
  CONNECT_PARTNER: 'CONNECT_PARTNER',
  REJECT_PARTNER_INVITATION: 'REJECT_PARTNER_INVITATION',
  REMOVE_PARTNER: 'REMOVE_PARTNER',
  UPDATE_PARTNER_JOIN_REQUEST: 'UPDATE_PARTNER_JOIN_REQUEST',
  VIEW_PARTNER_DETAIL: 'VIEW_PARTNER_DETAIL',
  VIEW_PARTNER_LIST: 'VIEW_PARTNER_LIST',

  // Brief
  VIEW_BRIEF_DETAIL: 'VIEW_BRIEF_DETAIL',
  VIEW_BRIEF_LIST: 'VIEW_BRIEF_LIST',
  CREATE_BRIEF: 'CREATE_BRIEF',
  DELETE_BRIEF: 'DELETE_BRIEF',
  UPDATE_BRIEF: 'UPDATE_BRIEF',
  CREATE_TEMPLATE_BRIEF: 'CREATE_TEMPLATE_BRIEF',

  // Permissions & roles
  CLIENT_CREATE_ROLE: 'CLIENT_CREATE_ROLE',
  CLIENT_DELETE_ROLE: 'CLIENT_DELETE_ROLE',
  CLIENT_UPDATE_ROLE: 'CLIENT_UPDATE_ROLE',
  CLIENT_VIEW_DETAIL_ROLE: 'CLIENT_VIEW_DETAIL_ROLE',
  CLIENT_VIEW_LIST_ROLE: 'CLIENT_VIEW_LIST_ROLE',
  // CLIENT_UPDATE_ROLE_PERMISSIONS: 'CLIENT_UPDATE_ROLE_PERMISSIONS',
};

export const ADMIN_PERMISSIONS = {
  // Client management
  CREATE_APPROVED_CLIENT_USER: 'CREATE_APPROVED_CLIENT_USER',
  CREATE_CLIENT: 'CREATE_CLIENT',
  DELETE_APPROVED_CLIENT_USER: 'DELETE_APPROVED_CLIENT_USER',
  DELETE_CLIENT: 'DELETE_CLIENT',
  DELETE_CLIENT_USER: 'DELETE_CLIENT_USER',
  REJECT_REQUEST: 'REJECT_REQUEST',
  APPROVE_REQUEST: 'APPROVE_REQUEST',
  UPDATE_APPROVED_CLIENT_DETAIL: 'UPDATE_APPROVED_CLIENT_DETAIL',
  UPDATE_APPROVED_CLIENT_USER: 'UPDATE_APPROVED_CLIENT_USER',
  UPDATE_CLIENT: 'UPDATE_CLIENT',
  UPDATE_CLIENT_USER: 'UPDATE_CLIENT_USER',
  VIEW_DETAIL_APPROVED: 'VIEW_DETAIL_APPROVED',
  VIEW_DETAIL_CLIENT: 'VIEW_DETAIL_CLIENT',
  VIEW_DETAIL_REJECTED: 'VIEW_DETAIL_REJECTED',
  VIEW_DETAIL_REQUESTED: 'VIEW_DETAIL_REQUESTED',
  VIEW_LIST_APPROVED: 'VIEW_LIST_APPROVED',
  VIEW_LIST_CLIENT: 'VIEW_LIST_CLIENT',
  VIEW_LIST_REJECTED: 'VIEW_LIST_REJECTED',
  VIEW_LIST_REQUESTED: 'VIEW_LIST_REQUESTED',

  // Permissions & roles
  ADMIN_CREATE_ROLE: 'ADMIN_CREATE_ROLE',
  ADMIN_DELETE_ROLE: 'ADMIN_DELETE_ROLE',
  ADMIN_UPDATE_ROLE: 'ADMIN_UPDATE_ROLE',
  ADMIN_UPDATE_ROLE_PERMISSIONS: 'ADMIN_UPDATE_ROLE_PERMISSIONS',
  ADMIN_VIEW_DETAIL_ROLE: 'ADMIN_VIEW_DETAIL_ROLE',
  ADMIN_VIEW_LIST_ROLE: 'ADMIN_VIEW_LIST_ROLE',
};
